import json
import os

def refactor_deck_content(input_path, output_path):
    """
    Reads a deck file, refactors the 'content.value' for each card based on a predefined map,
    and saves the result to a new file.
    """
    print(f"Starting refactor for: {input_path}")

    # A comprehensive map of cardId to its new, pedagogically rich content value.
    # Syntax:
    # [word] -> Renders as blue text in UI (for correct option explanations).
    # ~word~ -> Renders as yellow text in UI (for incorrect option explanations).
    content_map = {
        "egac_001": "[Look at] is a prepositional verb phrase meaning to direct your sight towards something.\n\n~Look for~ means to search for something lost, which doesn't fit the context.\nAn empty option is incorrect as the verb ~look~ needs a preposition to connect to its object.",
        "egac_002": "[Enter] is a transitive verb of motion, meaning it doesn't require a preposition like 'to' before its object ('the building').\n\n~Go~ would require a preposition (e.g., 'go into the building').\n~Arrive~ also needs a preposition (e.g., 'arrive at the building') and typically marks the end of a journey.",
        "egac_003": "The structure [get + adjective] is a very common collocation used to describe a transition into a new state or feeling.\n\nUsing ~do~ or ~fall~ with an adjective like 'nervous' is not a standard grammatical structure in English for this meaning.",
        "egac_004": "The [Present Perfect Continuous] (has been + -ing) is used to emphasize the duration of an action that started in the past and continues to the present.\n\n~Is working~ (Present Continuous) describes an action happening now, not over a five-year period.\n~Works~ (Present Simple) describes a general habit but doesn't connect the past and present duration.",
        "egac_005": "[Used to] is the standard structure for talking about past habits or states that are no longer true.\n\n~Was playing~ (Past Continuous) describes an action in progress at a specific past moment, not a general habit over time.\n~Would~ can describe past habitual actions, but 'used to' is better for states and preferred when contrasting with the present.",
        "egac_006": "The structure [was/were going to + verb] is specifically used for plans or intentions made in the past that did not happen.\n\n~Would~ can express past intention, but it's less direct than 'were going to' in this context.\n~Went to~ (Past Simple) states that the action happened, which contradicts the fact that the trip was canceled.",
        "egac_007": "[Should have + past participle] is used to express regret or criticism about a past action that was advisable but didn't happen.\n\n~Must have~ expresses a logical deduction about the past (e.g., 'He must have been tired').\n~Can have~ is not a standard modal structure for expressing past possibility or regret.",
        "egac_008": "A [Gerund] (the -ing form of a verb) functions as a noun, making it the perfect choice for the subject of a sentence.\n\n~To read~ (infinitive) can be a subject, but it is much more formal and less common in everyday English.\n~Read~ (base verb) cannot be the subject of a sentence like this.",
        "egac_009": "The adjective 'interested' is part of a fixed prepositional phrase: [interested in]. Any verb following a preposition must be in its [Gerund] (-ing) form.\n\n~Interested to~ and ~interested for~ are grammatically incorrect collocations.",
        "egac_010": "The [Passive Voice] is required because the subject ('The final report') receives the action. The structure with a modal is [modal + be + past participle].\n\n~Submit~ is the active form, implying the report is performing the action.\n~To submit~ is an infinitive and doesn't fit the grammatical structure after 'must'.",
        "egac_011": "[Existential There] (there seems to be) is used to state that something exists or appears to exist, introducing it for the first time.\n\n~It seems to be~ is incorrect because 'it' must refer to a previously mentioned specific noun.\n~Has~ is a verb that doesn't fit the sentence structure and meaning.",
        "egac_012": "This is a [Subject Question] where the question word [Who] is the subject. In these questions, we do not use the auxiliary verb 'do/does/did'.\n\n~Who did~ and ~What did~ are incorrect structures for subject questions; they are used for object questions (e.g., 'Who did you see?').",
        "egac_013": "In modern English, it's natural to end a question with a preposition, especially when it's part of a phrasal verb like [look for].\n\n~For what are you looking~ is grammatically correct but extremely formal and unnatural in everyday conversation.\nAn empty option is incorrect as the phrasal verb is incomplete.",
        "egac_014": "The [Second Conditional] (If + Past Simple, ... would + base verb) is used for hypothetical or unlikely situations in the present or future.\n\n~will learn~ would be used in the First Conditional for a likely situation.\n~would have learned~ is for the Third Conditional, talking about a hypothetical past.",
        "egac_015": "The [Third Conditional] (would have + p.p. ... if + Past Perfect) is used to talk about hypothetical past situations and their unreal results.\n\n~studied~ (Past Simple) would be for the Second Conditional.\n~would have studied~ incorrectly places the 'would have' part in the 'if' clause.",
        "egac_016": "For [irregular plural nouns] that do not end in -s, like 'children', the possessive is formed by adding ['s], just like a singular noun.\n\n~childrens'~ is incorrect; the apostrophe after the 's' is for plural nouns that already end in 's'.\n~childrens's~ is a double possessive and grammatically incorrect.",
        "egac_017": "[Hairbrush] is a closed [Compound Noun], where the first noun acts as an adjective describing the purpose of the second. No possessive is needed.\n\n~hair's brush~ incorrectly implies possession (the hair owns the brush).\n~brush of hair~ describes a brush made of hair, not a brush for hair.",
        "egac_018": "Nouns like [police], [people], and [staff] are [Collective Nouns] that are always treated as plural, so they require a plural verb like [are].\n\n~is~ is a singular verb and therefore incorrect.\n~investigates~ is a singular verb form (he/she/it investigates).",
        "egac_019": "[Exhausted] is an 'extreme' or 'non-gradable' adjective, meaning it already implies 'very tired'. It must be intensified with adverbs like [absolutely] or [completely].\n\n~very~ is used with gradable adjectives (e.g., 'very tired'), not extreme ones.\n~little~ has the opposite meaning and doesn't fit the context.",
        "egac_020": "The adjective [busy] is one of a few special adjectives (like 'worth') that is followed directly by a [Gerund] (-ing form) without a preposition.\n\n~busy with~ and ~busy to~ are incorrect grammatical constructions in this context.",
        "egac_021": "[Turn down] is a separable phrasal verb. When the object is a pronoun (like 'it', 'him', 'them'), it [must] go between the verb and the particle.\n\n~turn down it~ is grammatically incorrect because the pronoun must be in the middle.\n~down turn it~ scrambles the word order of the phrasal verb.",
        "egac_022": "[Ran into] is an inseparable phrasal verb meaning to meet someone unexpectedly. The object must always come after the particle.\n\n~Looked for~ means to search intentionally.\n~Ran against~ means to compete against someone, for example in an election.",
        "egac_023": "The three-part phrasal verb is [run out of], which means to exhaust a supply of something.\n\n~run out~ is incomplete; you run out *of* something.\n~run of~ is not a correct phrasal verb.",
        "egac_024": "Indefinite pronouns like [Everybody], [someone], and [nobody] are grammatically singular and always take a singular verb like [is].\n\n~are~ and ~were~ are plural verbs and are therefore incorrect.",
        "egac_025": "In modern, inclusive English, the [Singular They] is used as a gender-neutral pronoun to refer to a single person whose gender is unknown or irrelevant.\n\n~he~ is outdated and not inclusive.\n~he or she~ is grammatically correct but less concise and common than 'they'.",
        "egac_026": "In English, physical sensations like hunger, cold, or thirst are described using the structure [to be + adjective] (e.g., I am hungry, I am cold).\n\n~have~ is a common error from languages like Spanish ('tener frío').\n~feel~ ('I feel cold') is also grammatically correct, but 'I am cold' is the most direct and common way to state the sensation.",
        "egac_027": "To agree with a positive statement, the correct structure is [So + auxiliary verb + subject]. The verb 'loves' is Present Simple, so the auxiliary is 'do'.\n\n~so I do~ has the incorrect word order; the verb and subject must be inverted.\n~I do also~ is understandable but not the standard, idiomatic structure for this type of short agreement.",
        "egac_028": "For exclamations about a noun phrase, the structure is [What + a/an + (adjective) + noun]!\n\n~How~ is used for exclamations with an adjective or adverb alone (e.g., 'How beautiful!').\n~How a~ is an incorrect structure.",
        "egac_029": "A [lack] (noun) refers to a general deficiency or not having enough of an abstract quality like 'experience'.\n\n~shortage~ is typically used for a quantifiable lack of concrete things (e.g., 'a food shortage').\n~loss~ implies the experience was once possessed and then taken away, which is a different meaning.",
        "egac_030": "For years in the 20th century (the 1900s), the standard pronunciation is to split the year into two two-digit numbers: [nineteen ninety-five].\n\n~one thousand...~ is very formal and rarely used in speech.\n~ninety-five~ is incomplete.",
        "egac_031": "The structure for comparing two general activities is [prefer + gerund + to + gerund]. The 'to' here is a preposition, not part of an infinitive.\n\n~go~ and ~to go~ are incorrect because a gerund (-ing form) must follow the preposition 'to' in this structure.",
        "egac_032": "The structure [would rather + base verb + than + base verb] is used for specific preferences. No 'to' or '-ing' is used after 'would rather'.\n\n~to read~ and ~reading~ are incorrect verb forms for this specific structure.",
        "egac_033": "A [Reflexive Pronoun] (himself, myself, etc.) is required when the subject of the verb is also the object of the verb. 'He' is the one teaching, and 'he' is the one being taught.\n\n~him~ would refer to a different male person.\n~to himself~ is grammatically incorrect.",
        "egac_034": "The [Past Perfect Continuous] (had been + -ing) is perfect for describing an action that was in progress for a period of time before another past action occurred.\n\n~was studying~ describes an action in progress, but doesn't emphasize the duration before the second event.\n~has been studying~ is the Present Perfect Continuous and would connect the action to the present, which is incorrect.",
        "egac_035": "The expression [is supposed to + verb] is used to talk about what is expected or planned to happen, often with a contrast to reality.\n\n~supposes to~ is not a correct grammatical form.\n~should to~ is incorrect; the modal 'should' is followed by a base verb without 'to'.",
        "egac_036": "In the common phrasal verb [look forward to], the word 'to' is a preposition. Therefore, it must be followed by a noun or a [Gerund] (-ing form).\n\n~to see~ is a common error, mistaking the 'to' for part of an infinitive.\n~see~ is the base form and is incorrect.",
        "egac_037": "An [Infinitive of Purpose] (to + verb) is used to explain the reason or goal of an action. She practices *for the purpose of* improving.\n\n~for improving~ is not the standard way to express purpose in this structure.\n~improving~ by itself doesn't express the purpose of the action 'practicing'.",
        "egac_038": "The structure to ask what action someone desires from another person is [Want + Object Pronoun + to-infinitive].\n\n~that I do~ and ~I do~ are incorrect structures. English avoids using a 'that'-clause after 'want' in this context.",
        "egac_039": "The correct structure is [How long has it been since + subject + past simple affirmative verb?].\n\n~don't travel~ and ~didn't travel~ are incorrect because a negative verb is not used in the 'since' clause of this specific question format.",
        "egac_040": "The [First Conditional] describes a real possibility in the future. The structure is: [If + Present Simple], ... [will + base verb].\n\n~will study~ is incorrect; 'will' is not used in the 'if' clause of a conditional sentence.\n~would study~ would be for a hypothetical situation (Second Conditional).",
        "egac_041": "For regular plural nouns that already end in 's', like 'parents', the possessive is formed by adding only an apostrophe ['] after the 's'.\n\n~parent's~ is the singular possessive (one parent).\n~parents's~ is grammatically incorrect.",
        "egac_042": "[Proud of] is a fixed adjective-preposition collocation. You are always proud *of* something or someone.\n\n~proud for~ and ~proud with~ are incorrect prepositions to use with 'proud'.",
        "egac_043": "[Build up] is a phrasal verb meaning to increase or strengthen gradually. When the object ('your confidence') is a noun phrase, it can come after the particle.\n\n~build your confidence up~ is also correct, as the phrasal verb is separable. However, the first option is a valid and common structure.\n~build off~ is an incorrect phrasal verb for this meaning.",
        "egac_044": "The three-part phrasal verb [cut down on] specifically means to reduce the consumption of something.\n\n~cut off~ usually means to interrupt or stop a supply completely.\n~cut~ by itself is incomplete and lacks the meaning of reduction.",
        "egac_045": "[Call off] is a separable phrasal verb that means to cancel a planned event.\n\n~call out~ means to shout or to summon someone (like a plumber).\n~call up~ means to telephone someone.",
        "egac_046": "[Gotta] is the standard informal, spoken contraction of 'have got to', expressing necessity.\n\n~got to~ is the un-contracted form, but 'gotta' is more natural in this very informal sentence.\n~must to~ is incorrect; 'must' is a modal verb and is not followed by 'to'.",
        "egac_047": "['ve got] (have got) is a common, slightly informal alternative to 'have' for expressing possession in the present.\n\n~am got~ is grammatically incorrect.\n~got~ by itself is technically the simple past, though it's often used informally in the present; 'have got' is the more standard present form being tested.",
        "egac_048": "To agree using 'too', you must use the auxiliary or 'be' verb that matches the original statement's tense. The original statement was in the past ('she was tired'), so the agreement must also be in the past [was].\n\n~am~ is present tense.\n~have~ is the wrong verb entirely.",
        "egac_049": "For exclamations with just an adjective or adverb, the correct structure is [How + adjective/adverb]!\n\n~What~ and ~What an~ are used when a noun is present in the exclamation (e.g., 'What an interesting idea!').",
        "egac_050": "[Out of] is a fixed phrasal expression used to describe the state of having completely exhausted a supply of something.\n\n~missing of~ is grammatically incorrect. 'Missing' is used for a specific lost item.\n~Lacking~ is used for a general deficiency, but the sentence structure would be different (e.g., 'we lack coffee').",
        "egac_051": "[In the meantime] is a standard phrase introducing what can be done while waiting for something else. 'Meanwhile' is also correct and slightly more common in speech.\n\n~During~ must be followed by a noun (e.g., 'during the week').\n~While~ must be followed by a clause (e.g., 'while we wait').",
        "egac_052": "[Make a mistake] is a fixed collocation. A collocation is a group of words that are frequently used together by native speakers.\n\n~do a mistake~ and ~have a mistake~ are common errors for learners.",
        "egac_053": "A [Past Participle] (like 'broken', 'written') is used as an adjective before a noun to describe its state as a result of a past action.\n\n~broke~ is the simple past tense verb.\n~break~ is the base verb.",
        "egac_054": "[Inversion] is used for emphasis when a sentence starts with a negative adverb like [Never]. The auxiliary verb ('have') comes before the subject ('I').\n\n~Hardly~ would also work grammatically but changes the meaning slightly. 'Never' is a stronger fit for the context.\n~Never I~ is incorrect because it's missing the required inversion.",
        "egac_055": "A [Cleft Sentence] with [It was...] is used to focus on a particular piece of information (here, 'the engineering team'). The structure is [It was + focused info + that/who...].\n\n~The engineering team was~ is a simple statement, lacking the specific emphasis.\nThe third option is a long, grammatically malformed fragment.",
        "egac_056": "A [Cleft Sentence] with [What...] is used to focus on the object or action. The structure is [What-clause + verb 'to be' + focused info].\n\n~The thing what we need~ is redundant and ungrammatical.\n~That we need~ is a noun clause, but it doesn't create the emphatic 'What' cleft structure.",
        "egac_057": "The [Zero Conditional] (If + Present Simple, ... Present Simple) is used for facts and general truths that are always true.\n\n~will melt~ would imply a specific future event (First Conditional), not a scientific fact.\n~melted~ is past tense and incorrect.",
        "egac_058": "[Had better] is a modal expression for strong advice, implying a negative consequence if not followed. It is followed by the base verb without 'to'.\n\n~have better~ is a common grammatical mistake.\n~had better to~ is incorrect, as 'to' should not be used.",
        "egac_059": "A [Quarter] is a US coin worth 25 cents, commonly used in vending machines.\n\n~A Penny~ is worth 1¢.\n~A Nickel~ is worth 5¢.",
        "egac_060": "[Despite] is a connector of contrast that must be followed by a noun or a gerund (-ing form).\n\n~because of~ shows a reason, not a contrast.\n~although~ also shows contrast, but it must be followed by a full clause (subject + verb), not a gerund.",
        "egac_061": "With [Causative Verbs of Emotion], the subject ('the news') causes the feeling in the object ('the team'). The active verb [excited] is correct.\n\n~was excited by~ is passive voice, which is awkward here.\n~impressed~ is possible but 'excited' is a stronger and more direct fit for 'success'.",
        "egac_062": "[Would] is used to talk about repeated, habitual actions in the past (not states), and is common in nostalgic storytelling.\n\n~used to telling~ is grammatically incorrect.\n~was telling~ (Past Continuous) implies a single, interrupted action, not a repeated habit.",
        "egac_063": "A [Gerund] (-ing form) is used after fixed expressions like [have trouble] or [have difficulty].\n\n~trouble to find~ is incorrect; an infinitive is not used here.\n~trouble for finding~ is grammatically incorrect.",
        "egac_064": "[Therefore] is a formal connector that means 'for that reason' or 'as a result', linking a cause to its logical effect.\n\n~despite~ shows contrast.\n~besides~ adds an additional reason.",
        "egac_065": "[However] is a connector used to introduce a statement that contrasts with or contradicts the previous one.\n\n~Therefore~ shows a result.\n~Because~ shows a reason.",
        "egac_066": "'Good' is an [Irregular Adjective]. Its comparative form is [better].\n\n~gooder~ and ~more good~ are common errors and are grammatically incorrect.",
        "egac_067": "The expression [good at] is a fixed prepositional phrase used to talk about ability or skill in a particular area.\n\n~well~ is an adverb, not an adjective, in this context.\n~fond~ is followed by 'of' ('fond of') and means to like something.",
        "egac_068": "The phrasal verb [show off] means to try to impress others by displaying your possessions or abilities proudly.\n\n~show up~ means to arrive.\n~show over~ is not a standard phrasal verb.",
        "egac_069": "[Mine] is a [Possessive Pronoun] that replaces a possessive adjective + noun ('my coat') to avoid repetition.\n\n~My~ is a possessive adjective and must be followed by a noun.\n~Me~ is an object pronoun.",
        "egac_070": "[Do business] is a fixed collocation. Learning these natural word pairings is key to sounding fluent.\n\n~make business~ and ~have business~ are not the standard expressions in this context.",
        "egac_071": "[Inversion] is required when a sentence starts with 'Not only'. The structure is [Not only + Auxiliary + Subject + Main Verb].\n\n~Not only she~ and ~She not only~ are incorrect because they lack the required subject-verb inversion for emphasis.",
        "egac_072": "[Inversion] must be used when a sentence begins with [Hardly]. The auxiliary verb ('had') comes before the subject ('I').\n\n~Hardly I~ and ~I hardly~ are incorrect because they lack the required inversion.",
        "egac_073": "A [Cleft Sentence] with [What... did was...] puts strong focus on an action. The verb after 'was' is in its base form.\n\n~The thing what he did~ is ungrammatical.\n~What did he~ is an interrogative structure, not a cleft sentence.",
        "egac_074": "The [Past Perfect Simple] (had + past participle) is used to show that one past event happened before another past event.\n\n~already started~ (Past Simple) doesn't clearly establish the sequence of events.\n~has already started~ (Present Perfect) connects the event to the present, which is incorrect.",
        "egac_075": "The [Future Continuous] (will be + -ing) is used to talk about an action that will be in progress at a specific time in the future.\n\n~will have~ describes a completed action in the future.\n~am having~ is for a fixed arrangement, which is possible but 'will be having' better describes an action in progress.",
        "egac_076": "[Imperative Sentences] give commands or instructions. They start with the base form of the verb, and the subject 'you' is implied.\n\n~You drink~ is a statement, not a command.\n~To drink~ is an infinitive and cannot start a command.",
        "egac_077": "Compound nouns describing family relations like [mother-in-law] are written with hyphens.\n\n~mother in law~ (without hyphens) is a common error.\n~mother's in law~ incorrectly uses a possessive.",
        "egac_078": "[Afraid of] is a fixed adjectival phrase. The adjective 'afraid' must be followed by the preposition 'of'.\n\n~fear~ is a noun or verb, not an adjective.\n~scaring~ is the present participle; the sentence requires an adjective describing the person's feeling.",
        "egac_079": "When a number and noun (e.g., twenty dollar) are used as a compound adjective before another noun ('bill'), the noun part of the adjective is [singular].\n\n~twenty-dollars bill~ is a common error; the adjective form should be singular.\n~twenty of dollars bill~ is grammatically incorrect.",
        "egac_080": "A [Past Participle] (like 'written') can be used as an adjective before a noun to describe its state as the result of an action.\n\n~wrote~ is the simple past verb.\n~writing~ (Present Participle) would mean the report is actively writing something, which is illogical.",
        "egac_081": "The expression [be used to] means 'be accustomed to'. The 'to' is a preposition, so it must be followed by a noun or a [Gerund] (-ing form).\n\n~am used to wake~ is a common error, mistaking 'to' for part of an infinitive.\n~used to~ refers to a past habit, a different meaning.",
        "egac_082": "The [Impersonal They] is used to make general statements or report what 'people in general' say or believe.\n\n~It~ is used for impersonal statements of fact or opinion (e.g., 'It is said that...').\n~People~ is also correct, but 'They' is a very common and natural-sounding impersonal pronoun.",
        "egac_083": "A [Nominal Clause] (or Noun Clause) can act as the subject of a sentence. [Who committed the crime] is the entire subject of the verb 'is'.\n\n~That~ is not the correct word to introduce this type of noun clause about an unknown person.\n~Which~ is used for choices among a known set of options.",
        "egac_084": "[Besides] is a connector used to introduce an additional, often stronger, reason for something.\n\n~Despite~ shows contrast.\n~However~ also shows contrast.",
        "egac_085": "[Except for] is a connector of exclusion, used to single out the only person or thing to which a statement does not apply.\n\n~apart~ would need 'from' ('apart from Tom').\n~besides~ means 'in addition to', which is the opposite meaning.",
        "egac_086": "'Starving' is an [Extreme Adjective]. It already means 'very hungry' and cannot be modified by 'very'. Instead, use intensifiers like [absolutely].\n\n~very~ is used with gradable adjectives (very hungry), not extreme ones.\n~really~ can sometimes be used, but 'absolutely' is a stronger and more common collocator with 'starving'.",
        "egac_087": "[Heavy rain] is the standard, fixed collocation in English. Words that naturally go together are called collocations.\n\n~strong rain~ and ~powerful rain~ are understandable but are not the natural word pairings used by native speakers.",
        "egac_088": "[Meanwhile] is an adverb meaning 'in the period of time between two events'. It's very common in everyday speech.\n\n~During~ must be followed by a noun phrase (e.g., 'during the hour').\n~In time~ means 'eventually' or 'before a deadline', which is a different meaning.",
        "egac_089": "For [years before 2000], the standard pronunciation is to split the year into two pairs of numbers: [nineteen twelve].\n\n~one thousand nine hundred twelve~ is very formal and rarely used.\n~ninety twelve~ is an incorrect combination.",
        "egac_090": "A [dime] is a US coin worth 10 cents. Knowing US coin vocabulary is essential for daily transactions.\n\n~A nickel~ is worth 5¢.\n~A penny~ is worth 1¢.",
        "egac_091": "The verb [insist] is a prepositional verb that must be followed by the preposition [on] before its object or a gerund.\n\nAn empty option is incorrect; the preposition is not optional.\n~to~ is the incorrect preposition.",
        "egac_092": "The [Present Perfect Simple] (have/has + past participle) is used for recent past actions that have a direct relevance or result in the present (the 'Great news!').\n\n~was passing~ (Past Continuous) describes an action in progress in the past.\n~did pass~ (Past Simple with emphasis) would be used if the specific time was important and already mentioned.",
        "egac_093": "The [Present Perfect Simple], often with [ever], is the standard tense for asking about general life experiences at an unspecified time before now.\n\n~Did you ever go~ (Past Simple) asks about a specific, finished time in the past.\n~Were you ever going~ is an unlikely and grammatically awkward construction.",
        "egac_094": "Use [will] (contracted to 'll) for spontaneous decisions, offers, or promises made at the moment of speaking.\n\n~'m going to get~ implies a pre-existing plan, which doesn't fit the context of the phone suddenly ringing.\n~'m getting~ is for fixed future arrangements.",
        "egac_095": "Use [be going to] to talk about future plans and intentions that have been decided before the moment of speaking.\n\n~will try~ would suggest a spontaneous decision rather than a plan for 'next year'.\n~are trying~ (Present Continuous) is for fixed arrangements, which is less appropriate for a general intention like this.",
        "egac_096": "The [Present Continuous] is often used for future plans that are fixed arrangements, like appointments with a specific time.\n\n~will see~ would be a spontaneous decision.\n~am going to see~ is also correct for a plan, but the Present Continuous is very common for scheduled events in a diary or calendar.",
        "egac_097": "Use [be going to] to make a prediction about the future based on clear, present evidence (the 'terrible traffic').\n\n~will be~ is for predictions based on opinion or general belief, not direct evidence.\n~are being~ is not a future form.",
        "egac_098": "The modal verb [can] is used to express general ability or skill in the present.\n\n~may~ is for permission or possibility.\n~must~ is for obligation.",
        "egac_099": "[May] is the most formal and polite modal verb for asking for permission.\n\n~Must~ expresses obligation, not permission.\n~Should~ is for giving advice.",
        "egac_100": "[Might] is a modal verb used to express a future possibility that you are not certain about. It fits perfectly with 'I'm not sure'.\n\n~must~ expresses a logical certainty.\n~can~ expresses ability or sometimes informal permission, not possibility in this context.",
        "egac_101": "[Declarative Questions] have the same grammar as a statement but use rising intonation to function as a question. They are common for confirming information.\n\nThe options ~are~ and ~why~ would create a standard interrogative sentence, but the sentence is already structured as a declarative statement needing only confirmation.",
        "egac_102": "When using multiple adjectives, they follow a standard order (OSASCOMP). The correct sequence here is [Opinion] (beautiful) -> [Size] (long) -> [Color] (red).\n\nThe other options violate this standard ~adjective order~.",
        "egac_103": "Following the OSASCOMP rule for adjective order, the correct sequence is [Age] (old) -> [Origin] (German) -> [Purpose] (sports).\n\nThe other options scramble the standard ~adjective order~.",
        "egac_104": "For short, one-syllable adjectives like 'tall', the comparative is formed by adding [-er].\n\n~more tall~ is incorrect; 'more' is used with longer adjectives.\n~tall~ is the base form, not the comparative.",
        "egac_105": "For longer adjectives like 'difficult', the comparative is formed by placing [more] before the adjective.\n\n~difficulter~ is incorrect; the '-er' ending is for short adjectives.\n~as difficult~ is for an equality comparison ('as difficult as'), not a superiority comparison.",
        "egac_106": "The [superlative form] for short adjectives is [the + adjective + -est]. It is used to compare three or more items.\n\n~the most high~ is incorrect; 'most' is for long adjectives.\n~the higher~ is the comparative form, used for comparing two items.",
        "egac_107": "The [superlative form] for long adjectives is [the most + adjective]. It is often used with the present perfect ('I have ever...') to talk about life experiences.\n\n~the interestingest~ is incorrect; the '-est' ending is for short adjectives.\n~a most interesting~ is a different, more formal structure meaning 'a very interesting' and is not a true superlative.",
        "egac_108": "The modal verb [could] is the past tense of 'can' and is used to talk about a general skill or ability that someone possessed in the past.\n\n~can~ is for present ability.\n~may~ is for present permission or possibility.",
        "egac_109": "Use [be going to] to ask about someone's intentions or plans that they have already decided on ('I've decided').\n\n~will you study~ asks for a decision to be made now.\n~are you studying~ is for a fixed arrangement, which is less likely for a general plan like this.",
        "egac_110": "The [Present Perfect Simple] negative (haven't + p.p.) is used with [yet] to indicate that an expected action has not been completed up to the present moment.\n\n~didn't finish~ (Past Simple) refers to a specific, finished time in the past.\n~don't finish~ is present simple and doesn't fit with 'yet' in this context.",
        "egac_111": "The verb [depend] is a prepositional verb and must be followed by [on] or [upon] to connect it to its object. This is a fixed collocation.\n\n~of~ is the incorrect preposition.\nLeaving it empty is incorrect as the verb requires a preposition.",
        "egac_112": "The correct order for these adjectives is [Opinion] (beautiful) -> [Size] (small) -> [Material] (silver), following the standard OSASCOMP guideline.\n\nThe other options violate this standard ~adjective order~.",
        "egac_113": "The [comparative form] (the taller) is used when comparing exactly two items, even when 'the' is present. The superlative is for three or more.\n\n~the tallest~ is the superlative form and is incorrect for comparing only two things.\n~taller~ is missing the required article 'the' in this specific structure ('the... of the two').",
        "egac_114": "Use [will] for predictions based on personal opinion or belief, especially when introduced by phrases like 'I think'.\n\n~is going to be~ is for predictions based on present evidence, not opinion.\n~is being~ is not a future form.",
        "egac_115": "[May] is used to express a factual possibility. 'Might' is also correct and often interchangeable, but 'may' can suggest a slightly higher probability.\n\n~must~ expresses logical certainty.\n~should~ expresses advice or expectation.",
        "egac_116": "'Bad' is an [Irregular Adjective]. Its comparative is 'worse' and its superlative is [the worst].\n\n~the baddest~ and ~the more bad~ are grammatically incorrect forms.",
        "egac_117": "Following the OSASCOMP guideline, the correct adjective order is [Size] (small) -> [Shape] (square) -> [Material] (wooden).\n\nThe other options violate this standard ~adjective order~.",
        "egac_118": "When using a [comparative adjective] (like 'more intelligent'), the second item in the comparison is always introduced by the word [than].\n\n~that~ and ~as~ are incorrect conjunctions for this type of comparison.",
        "egac_119": "When using a [superlative] to identify the 'number one' within a group, the preposition [on] is used for groups like teams or committees. 'In' is often used for places.\n\n~than~ is for comparatives.\n~at~ is incorrect in this context.",
        "egac_120": "The verb [listen] is a prepositional verb and must always be followed by the preposition [to] when an object is mentioned.\n\n~at~ is incorrect.\nLeaving it empty is a common error; 'listen' is not transitive like 'hear'.",
        "egac_121": "[Coffee cup] is an open compound noun where the first noun ('coffee') acts as an adjective describing the purpose of the second ('cup').\n\n~coffee's cup~ incorrectly implies possession.\n~cup of coffee~ refers to the liquid beverage inside the cup, not the physical object itself.",
        "egac_122": "[Car door] is a standard open compound noun. The first noun modifies the second.\n\n~car's door~ is a common error that incorrectly implies possession.\n~door of the car~ is grammatically correct but much less common and natural than the compound noun.",
        "egac_123": "The [Impersonal It] is used to start sentences that state a general truth, opinion, or rule, acting as a 'dummy' subject.\n\n~Is a good idea~ is missing a subject.\n~That is a good idea~ would need to refer to a specific idea already mentioned.",
        "egac_124": "The [Impersonal You] is very common in English to refer to any person in general when stating a rule or general truth.\n\n~one~ is grammatically correct but very formal and much less common in everyday English.\n~a person~ is grammatically correct but less natural than 'you'.",
        "egac_125": "The [Impersonal Passive] structure [It + be + past participle + that-clause] is used to report opinions or beliefs held by people in general.\n\n~They are believed~ is not the correct impersonal structure.\n~It believes~ is active voice, implying 'it' has the capacity to believe.",
        "egac_126": "[Apart from] is a versatile connector. In this context, it means 'in addition to' or 'besides'.\n\n~Except~ would mean the cast was excellent but the main characters were not, which changes the meaning.\n~Besides~ has a similar meaning and would also be correct.",
        "egac_127": "The verb [apologize] requires the preposition [for] when followed by the reason. You apologize *to* a person *for* a mistake.\n\n~apologize~ is incomplete without the preposition.\n~apologize to~ would need to be followed by the person being apologized to.",
        "egac_128": "The expression [to treat oneself to something] is a fixed idiom using a reflexive pronoun ('myself'). It means to give yourself a special gift.\n\n~treated to myself~ has the incorrect word order.\n~treated me to~ is incorrect because the subject and object are the same person, requiring a reflexive pronoun.",
        "egac_129": "[Bus stop] is a standard open compound noun. The first noun describes the purpose of the second.\n\n~bus's stop~ incorrectly implies possession.\n~stop of the bus~ is grammatically correct but unnatural; the compound noun is the standard term.",
        "egac_130": "The structure [It is said that...] is a classic example of the impersonal passive voice, used to report widespread beliefs or rumors.\n\n~It said~ is active voice and incorrect.\n~They are said~ is not the correct impersonal structure.",
        "egac_131": "Verbs like [enjoy], [avoid], and [finish] must be followed by a [Gerund] (-ing form), not an infinitive.\n\n~to explore~ is an infinitive and is grammatically incorrect after 'enjoy'.\n~explore~ is the base form and is also incorrect.",
        "egac_132": "The verb [avoid] must be followed by a [Gerund] (-ing form).\n\n~to eat~ (infinitive) is a common grammatical error after 'avoid'.\n~eat~ (base form) is also incorrect.",
        "egac_133": "The verb [finish] requires a [Gerund] (-ing form) to follow it when referring to the completion of an activity.\n\n~to write~ (infinitive) and ~write~ (base form) are grammatically incorrect after 'finish'.",
        "egac_134": "The verb [mind] (in the sense of 'objecting to') is always followed by a [Gerund].\n\n~mind to~ is incorrect; 'mind' does not take an infinitive.\n~matter~ has a different meaning and doesn't fit the context.",
        "egac_135": "[Furniture] is an [uncountable collective noun]. It is always treated as singular and takes a singular verb like [is]. It also has no plural form.\n\n~furniture are~ is incorrect because the verb is plural.\n~furnitures are~ is incorrect because the noun cannot be pluralized.",
        "egac_136": "The noun [advice] is uncountable. It cannot be pluralized or used with the article 'a'. To count it, one must say 'a piece of advice'.\n\n~advices~ is a common error and is incorrect.\n~an advice~ is also incorrect as it treats an uncountable noun as countable.",
        "egac_137": "The noun [information] is uncountable in English. It always takes a singular verb like [is] and cannot be pluralized.\n\n~information are~ uses a plural verb for a singular noun.\n~informations are~ incorrectly pluralizes the noun.",
        "egac_138": "The adjective [worth] is followed directly by a [Gerund] (-ing form) to express that an activity is valuable or recommended.\n\n~worth to visit~ is a common error; 'worth' is not followed by an infinitive.\n~worthy of visiting~ is a different, more formal structure.",
        "egac_139": "The structure [worth + gerund] is consistent in questions, statements, and negatives.\n\n~worth to read~ and ~worth of reading~ are grammatically incorrect structures.",
        "egac_140": "The negative form of the expression is [it's not worth + gerund]. It's a common way to advise against a pointless activity.\n\n~worth to worry~ is an incorrect structure.\n~worthy worrying~ is also incorrect.",
        "egac_141": "The verb [get] is used with an adjective to show a change of state. It's more dynamic than 'to be'.\n\n~are~ describes a state, not the process of becoming dry.\n~put~ is the wrong verb and doesn't make sense here.",
        "egac_142": "[Getting] is the most natural and common way to describe a change that is currently in progress.\n\n~is being tired~ is grammatically incorrect for this meaning.\n~is becoming tired~ is also correct but more formal and less common in everyday speech than 'getting'.",
        "egac_143": "[Got] (the past of 'get') is used to describe a change of state that happened at a specific moment in the past.\n\n~was~ describes the state, while 'got' describes the transition into that state.\n~put~ is the wrong verb.",
        "egac_144": "In American English, [gotten] is the standard past participle of 'get' used to show a change or acquisition over time. ('He's' = 'He has').\n\n~been~ doesn't fit the structure ('has been much better').\n~had~ is the wrong verb.",
        "egac_145": "[Get some rest] is a fixed, idiomatic expression for 'to rest' or 'descansar'.\n\n~have some rest~ is understandable but much less common and idiomatic.\n~do some rest~ is grammatically incorrect.",
        "egac_146": "The standard collocation is [get help]. It means to seek or receive assistance.\n\n~take help~ and ~do help~ are not idiomatic in this context.",
        "egac_147": "[Might] is used to express a possibility that is uncertain. It perfectly captures the meaning of 'I'm not sure'.\n\n~can~ expresses ability, not possibility here.\n~will~ expresses certainty, which contradicts 'I'm not sure'.",
        "egac_148": "[May] is the traditional and more formal modal for asking permission. 'Can' is also common but more informal.\n\n~Might~ is not typically used to ask for permission.\n~Should~ is for asking for advice.",
        "egac_149": "[Had better] (contracted to 'd better) is used for strong advice, implying a negative consequence if ignored. It's followed by the base verb without 'to'.\n\n~should to~ and ~must to~ are grammatically incorrect.",
        "egac_150": "The negative form is [had better not]. The 'not' comes after the entire phrase.\n\n~don't had better~ and ~hadn't better~ are both incorrect negative constructions.",
        "egac_151": "[Don't have to] means there is no obligation; something is not necessary.\n\n~mustn't~ means something is prohibited, which is a very different meaning.\n~haven't to~ is grammatically incorrect.",
        "egac_152": "[Mustn't] expresses a strong prohibition; you are not allowed to do something.\n\n~don't have to~ means it's not necessary, which is too weak for a rule.\n~shouldn't to~ is incorrect grammar.",
        "egac_153": "The correct negative structure is [didn't use to + base verb]. 'Use' is in the base form because 'did' carries the past tense.\n\n~wasn't used to~ means 'I wasn't accustomed to', a different meaning.\n~didn't used to~ with a 'd' is a common spelling mistake.",
        "egac_154": "[Be used to] means to be familiar or accustomed to something. It describes a present state.\n\n~used to~ refers only to past habits.\n~'m use to~ is grammatically incorrect; it must be 'used'.",
        "egac_155": "The expression [be used to] must be followed by a noun or a gerund (-ing form).\n\n~used to~ by itself refers to a past habit.\n~'s used to work~ is incorrect because the structure requires a gerund, not an infinitive.",
        "egac_156": "[How's it going?] is a very common, informal greeting equivalent to 'How are you?'.\n\n~How's it doing?~ is not used as a greeting for a person.\n~How's it being?~ is grammatically incorrect.",
        "egac_157": "The phrasal verb [go on] means 'to happen'. 'What's going on?' is a standard question to ask about a current event or situation.\n\n~doing on~ and ~passing on~ are incorrect in this context.",
        "egac_158": "[Look like] is used to say that someone or something has a similar appearance to another.\n\n~look as~ and ~look to~ are incorrect for expressing visual comparison.",
        "egac_159": "[Sounds like] is used to give your impression of an idea or suggestion you've heard.\n\n~hears like~ and ~listens like~ are incorrect expressions for this context.",
        "egac_160": "[Feel like + gerund] is a common, informal way to say you want to do something.\n\n~feel as~ is incorrect.\n~am feeling to~ is grammatically wrong; it should be 'feel like'.",
        "egac_161": "[Raise] is a transitive verb, meaning you need to raise *something* (in this case, 'your hand').\n\n~Rise~ is intransitive; it means to go up by itself (e.g., 'The sun rises').\n~Arise~ means 'to emerge' or 'to appear' and doesn't fit here.",
        "egac_162": "[Rise] is an intransitive verb, meaning the subject ('the cost of living') goes up by itself. It doesn't need an object.\n\n~raise~ would require an object (e.g., 'The government raises taxes').\n~risen~ is the past participle and cannot follow 'to'.",
        "egac_163": "[End] is used for the natural conclusion of an event. Although many native speakers say 'finish' informally, 'end' is more precise.\n\n~finish~ implies an agent completing a task (e.g., 'I finished my homework').\n~complete~ is too formal for this everyday question.",
        "egac_164": "You [win] a prize, a game, or a competition.\n\n~beat~ is used for an opponent (e.g., 'We beat the other team').\n~gained~ means to acquire something over time and doesn't fit.",
        "egac_165": "You [beat] a person or a team. It means to defeat them in a competition.\n\n~won~ is used for the competition itself ('won the match'), not the opponent.\n~earned~ is for things acquired through work, like money or respect.",
        "egac_166": "[Earn] is used for things you get as a deserved reward for your labor, like a salary, respect, or a promotion.\n\n~gained~ is for acquiring things gradually (like weight or experience).\n~won~ is for competitions.",
        "egac_167": "[Gain] is the most appropriate verb for acquiring or increasing abstract things like experience, knowledge, or weight.\n\n~earned~ implies a direct reward for a specific task.\n~beaten~ means to defeat and is incorrect.",
        "egac_168": "You use [wait] without a preposition when the object is understood from context. The focus is on the duration.\n\n~waiting for~ needs an object (e.g., 'waiting for me').\n~expecting~ means to anticipate and is less common in this specific greeting.",
        "egac_169": "[Set an alarm] is a fixed, standard collocation.\n\n~Put my alarm~ is not idiomatic.\n~Program my alarm~ is understandable but overly technical; 'set' is the everyday verb.",
        "egac_170": "The fixed expression is [set the table].\n\n~make the table~ and ~put the table~ are incorrect in this context.",
        "egac_171": "[Take a look] is a very common idiom meaning to examine something briefly.\n\n~give a look~ and ~make a look~ are not standard English expressions.",
        "egac_172": "The idiom [take place] is the standard way to say that an event will happen.\n\n~have place~ and ~make place~ are incorrect.",
        "egac_173": "[Take advantage of] is the correct idiom for utilizing an opportunity.\n\n~have advantage of~ and ~get advantage of~ are not standard English expressions.",
        "egac_174": "[So] is used before an adjective to add strong emotional emphasis. 'Very' and 'really' are also correct, but 'so' is the most emphatic and natural choice.\n\n~much~ and ~a lot~ are not used to modify adjectives directly like this.",
        "egac_175": "[Ever] is used in questions with the Present Perfect to ask about life experiences.\n\n~never~ is for negative statements, not questions.\n~yet~ is used for actions expected to happen, usually in negatives and questions about recent events.",
        "egac_176": "[Ever] is used after a superlative (like 'the best') to emphasize it's the most extreme example in one's life experience.\n\n~never~ would make the sentence illogical.\n~always~ doesn't fit the grammatical structure.",
        "egac_177": "[Ago] is always placed after the time period and is used only with the Past Simple tense.\n\n~before~ is a preposition or conjunction used differently (e.g., 'I saw him before the meeting').\n~past~ is not used in this way to mark time.",
        "egac_178": "[Even] is used to emphasize something that is surprising or unexpected.\n\n~also~ and ~too~ are for adding information, but they lack the element of surprise that 'even' provides.",
        "egac_179": "[Not even] is the structure used to emphasize a surprising negative. In this sentence, 'couldn't' provides the 'not'.\n\n~neither~ and ~either~ are used for agreement and choice, not for this kind of emphasis.",
        "egac_180": "[I'd rather] (I would rather) is the common way to state a preference in a specific situation. It's followed by a base verb.\n\n~I'd prefer~ needs an infinitive ('to have').\n~I'd better~ is for strong advice, not preference.",
        "egac_181": "The adjective [worth] is followed directly by a noun (like 'the climb') or a gerund.\n\n~Worthy~ needs a preposition ('worthy of the climb').\n~good for~ has a different meaning (beneficial for).",
        "egac_182": "[Capable of] is the correct fixed phrase. It must be followed by a noun or gerund.\n\n~capable to~ is incorrect. The adjective 'able' uses an infinitive ('able to solve').\n~able of~ is grammatically incorrect.",
        "egac_183": "The structure for equality comparisons is [as + adjective + as]. In negative sentences, 'so' can sometimes replace the first 'as', but 'as...as' is always correct and more common.\n\n~like~ is used for similarity but not in this grammatical structure.",
        "egac_184": "The correct fixed expression is [the same as].\n\n~the same that~ is a common error from Spanish speakers.\n~same like~ is grammatically incorrect.",
        "egac_185": "[Most of] is used before a specific, defined group (e.g., 'the people', 'my friends').\n\n~Mostly~ is an adverb meaning 'mainly' (e.g., 'The people were mostly students').\n~The most of~ is incorrect.",
        "egac_186": "[Mostly] is an adverb that modifies the verb or clause, meaning 'mainly' or 'predominantly'.\n\n~most~ would need 'of' ('most of the attendees').\n~most of~ is a quantifier, not an adverb describing the group's origin.",
        "egac_187": "[Left] is used as an adjective after a noun to indicate the quantity that remains.\n\n~remaining~ is also correct but much more formal and less common in everyday speech.\n~still~ is an adverb and doesn't fit grammatically here.",
        "egac_188": "[Gone] is used as an adjective with the verb 'to be' to mean 'exhausted' or 'no longer present'.\n\n~finished~ implies someone completed the act of eating it. 'Gone' just describes the state.\n~left~ is the opposite meaning.",
        "egac_189": "[Awkward] is the perfect word for situations that are socially uncomfortable or embarrassing.\n\n~Weird~ or ~odd~ silence is possible, but it suggests the silence itself was strange, not that the situation was socially uncomfortable.",
        "egac_190": "[Strange] is used for things that are uncommon or unexpected. It's more neutral than 'weird'.\n\n~awkward~ is for social discomfort.\n~off~ implies something is wrong or incorrect, which doesn't fit."
    }

    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            deck_data = json.load(f)
    except FileNotFoundError:
        print(f"Error: Input file not found at {input_path}")
        return
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from {input_path}")
        return

    # Loop through cards and update the content value
    updated_count = 0
    missed_cards = []
    for card in deck_data.get("cards", []):
        card_id = card.get("cardId")
        if card_id and card_id in content_map:
            if "content" not in card:
                card["content"] = {}
            
            card["content"]["type"] = "text"
            card["content"]["value"] = content_map[card_id]
            updated_count += 1
        elif card_id:
            missed_cards.append(card_id)

    print(f"Refactor complete. Updated {updated_count} of {len(deck_data.get('cards', []))} cards.")
    if missed_cards:
        print(f"Warning: The following cardIds were not found in the map and were NOT updated: {missed_cards}")


    # Save the updated deck to the new file
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(deck_data, f, ensure_ascii=False, indent=2)
        print(f"Successfully saved updated deck to: {output_path}")
    except Exception as e:
        print(f"Error saving file to {output_path}: {e}")


if __name__ == '__main__':
    # --- CONFIGURATION ---
    INPUT_DECK_PATH = os.path.join('public', 'data', 'english_grammar_audio_choice.json')
    
    filename, ext = os.path.splitext(INPUT_DECK_PATH)
    OUTPUT_DECK_PATH = f"{filename}_updated{ext}"
    
    # --- EXECUTION ---
    refactor_deck_content(INPUT_DECK_PATH, OUTPUT_DECK_PATH)